### ISSUE TITLE
Github-style status badges?

### ISSUE THREAD

**Issue by zahhar** [halfmoonui/halfmoon#2] opened 2020-07-10 06:33 UTC
Hi,

Halfmoon is amazing project, thank you for starting it. 
Now I am working on a status page and I am missing Github-style badges. 
Bootstrap does not have it either, and all badge generators I found (e.g. shields.io) provide only images, but not the markup.

So I came up with something that covers my needs, take a look: https://jsfiddle.net/zahhar/8ezmnLy9/3/

Will be happy to improve (dark mode, links, unification with existing badges - you name it) and create PR if you think this is valuable addition to Halfmoon.

**Comment by halfmoonui** [comment] 2020-07-10 12:44
Hey, thanks for the kind words. Regarding the image based status badges, I think the main reason for providing support for images only (and not markup) is because these images are **mostly** used on READMEs. However, this is certainly not a bad idea. Halfmoon has a few missing group components, namely button groups, so badge groups could also be a nice addition.

**Comment by zahhar** [comment] 2020-07-12 09:50
@halfmoonui - may I ask you to share some tips for contributors? I am not sure if I should change halfmoon-variables.css or halfmoon.css, for example. Or probably you actually have source files  for every component + variables file separately, that get linted together into resulting halfmoon.css?

Anyhow, appreciate some guidance before I create a PR.

**Comment by halfmoonui** [comment] 2020-07-12 15:52
@zahhar Yes sure. Basically, I do not have source files for every component, instead it is just the two monoliths. I usually add  the changes the `halfmoon-variables.css` file first, and then to the `halfmoon.css` file. If everything works as expected, the code is minified and pushed to git.

**Comment by haguezoum** [comment] 2020-07-12 16:10
I hope you download Halfmoon for smooth Angular use
Thank you


Le dim. 12 juil. 2020 à 16:52, Halfmoon UI <notifications@github.com> a
écrit :

**Comment by halfmoonui** [comment] 2020-09-16 16:23
@zahhar This has been added in v1.1.0. Link: https://www.gethalfmoon.com/docs/badges/#badge-group

I will go ahead and close this issue. You can re-open it if you think the issue is still not resolved, or open another issue.

**Closed by halfmoonui** 2020-09-16 16:23 UTC
Labels: enhancement
