### ISSUE TITLE
FR: Add progress indicator components

### ISSUE THREAD

**Issue by Shanzid01** [halfmoonui/halfmoon#7] opened 2020-07-22 18:04 UTC
Personal opinion, but I think having a progress indicator component (like a linear or circular progress) is going to be very helpful.

**Comment by halfmoonui** [comment] 2020-07-23 10:48
Sounds like a good idea. I will label this.

**Comment by halfmoonui** [comment] 2020-09-16 16:24
@Shanzid01 Progress indicators have been added in v1.1.0. Link: https://www.gethalfmoon.com/docs/progress/

I will go ahead and close this issue. You can re-open it if you think the issue is still not resolved, or open another issue.

**Closed by halfmoonui** 2020-09-16 16:24 UTC
Labels: enhancement
