### ISSUE TITLE
Change of cookie to local-storage

### ISSUE THREAD

**Issue by obonyojimmy** [halfmoonui/halfmoon#46] opened 2020-09-18 18:10 UTC
Leverage use local-storage `window.localStorage()` for storing internal states instead of cookies.

**Comment by wopian** [comment] 2020-09-18 19:32
Possible duplicate of https://github.com/halfmoonui/halfmoon/issues/30

**Comment by halfmoonui** [comment] 2020-09-19 10:03
Yep, this is a duplicate of https://github.com/halfmoonui/halfmoon/issues/30. Please refer to that issue where this has been discussed and resolved.

**Closed by halfmoonui** 2020-09-19 10:03 UTC
Labels: duplicate
