### ISSUE TITLE
Sidebar white flash, dark mode

### ISSUE THREAD

**Issue by mattbingham** [halfmoonui/halfmoon#28] opened 2020-08-21 19:44 UTC
Hi. I'm using the framework to build in python with  Flask. I have the dark mode switcher available and using the documented script to save the users light/dark preference.

The preference saves just fine, but often the sidebar will flash white when changing views before returning to the saved dark setting (if dark is set).

Here's a quick view that will show you the flashing issue:

https://www.loom.com/share/a09678cdca0a4ad5b6ee06361c7d4bc7

I have several switches set depending on screen size. Unsure if that would cause this issue?

**Comment by halfmoonui** [comment] 2020-10-06 21:32
@mattbingham Hey, I hope you have found the solution to your problem. This issue has also been addressed in the docs: https://www.gethalfmoon.com/docs/core-javascript-library/#slight-delay-before-setting-the-preferred-mode

I will go ahead and close it. You can re-open it if you think the issue is still not resolved, or open another issue. Thank you.

**Closed by halfmoonui** 2020-10-06 21:32 UTC

**Comment by mattbingham** [comment] 2020-10-22 21:16
> @mattbingham Hey, I hope you have found the solution to your problem. This issue has also been addressed in the docs: https://www.gethalfmoon.com/docs/core-javascript-library/#slight-delay-before-setting-the-preferred-mode
> 
> I will go ahead and close it. You can re-open it if you think the issue is still not resolved, or open another issue. Thank you.

I haven't had chance to test this but will give you a poke if the fix doesn't work. Thanks for the update (and sorry for the delay).
