### ISSUE TITLE
Rounded buttons

### ISSUE THREAD

**Issue by alex3025** [halfmoonui/halfmoon#25] opened 2020-08-18 08:25 UTC
Will rounded buttons be added?

And, thanks for this beautiful framework!

**Comment by halfmoonui** [comment] 2020-08-18 17:50
Seems like a good idea, I will mark it.

**Comment by halfmoonui** [comment] 2020-10-06 21:04
@alex3025 This has been added in v1.1.1: https://www.gethalfmoon.com/docs/buttons/#rounded-buttons

I will go ahead and close this issue. You can re-open it if you think the issue is still not resolved, or open another issue. Thank you.

**Closed** 2020-10-06 21:05 UTC
Labels: enhancement
