### ISSUE TITLE
Inconsistent transition speeds

### ISSUE THREAD

**Issue by toman222** [halfmoonui/halfmoon#34] opened 2020-08-28 06:53 UTC
Seen on Google Chrome, at the Introduction page of the Docs
Toggling between dark and light theme shows that some elements have different transition speeds.
The sidebar is clearly slower than the rest of the page, and the text outside of cards transitions slower than that inside

**Comment by halfmoonui** [comment] 2020-08-28 18:12
Fair point. But how do you propose we fix this? The sidebar needs a transition for the toggle to be smooth. This unfortunately makes it slow during dark mode toggles.

Not sure about the text outside of the card though.

**Comment by toman222** [comment] 2020-08-29 12:03
By giving everything else the same transition speed?

**Comment by halfmoonui** [comment] 2020-08-29 14:11
Giving everything the same transition is a bad idea. You would get a delay on mundane things like the hover and focus effects on button. And the difference in speed is precisely why the sidebar toggle is so snappy. I think there **might** be a possible solution to this, but it would require JavaScript. Removing all the transitions is another way.

**Comment by toman222** [comment] 2020-08-29 15:20
Maybe just adjust the transition speed for the necessary properties then?

**Comment by halfmoonui** [comment] 2020-09-16 16:26
@toman222 Fixed in v1.1.0: https://www.gethalfmoon.com/docs/introduction/

I will go ahead and close this issue. You can re-open it if you think the issue is still not resolved, or open another issue.

**Closed by halfmoonui** 2020-09-16 16:26 UTC
