### ISSUE TITLE
The size of elements is significantly bigger than the default and other frameworks when >=1600px

### ISSUE THREAD

**Issue by torchatlas** [halfmoonui/halfmoon#44] opened 2020-09-18 01:52 UTC
I discovered this framework recently, and it looks really cool, but one thing really popped out when I added this to a project: the size of elements.

When I added this to one of my projects, there was a very noticeable increase in the size of all the elements. To illustrate this, here's the Halfmoon documentation page, compared to the Bootstrap documentation page.

![image](https://user-images.githubusercontent.com/12666855/93545786-4edb5e80-f92f-11ea-9d41-576094462855.png)
![image](https://user-images.githubusercontent.com/12666855/93545821-674b7900-f92f-11ea-8160-06ba65675382.png)

I fixed this for the most part by decreasing my root font size, but I was wondering: is this intentional? Because I think it may be better to have the size be similar to what people are used to.

However, <1600px, where there isn't auto-scaling, things look standard.

**Comment by halfmoonui** [comment] 2020-09-18 01:56
This is definitely on purpose. On really large screens, most websites work poorly in my opinion, because **a ton** of space is wasted. However, this can be turned off with the class `.auto-scaling-disabled` on the `<html>` element. It has a section in the docs: https://www.gethalfmoon.com/docs/page-building/#auto-scaling

So if you prefer it turned off, just add the class and you are good to go.

**Comment by halfmoonui** [comment] 2020-10-06 21:13
Since I believe this issue has been resolved, I will go ahead and close it. You can re-open it if you think the issue is still not resolved, or open another issue. Thank you.

**Closed by halfmoonui** 2020-10-06 21:13 UTC
